# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dream.Code.Sleep.Repeat.
email: oatto.paul@gmail.com
author: Powell-v2
permalink: /pages/blog/:year/:month/:day/:title/
description: > # this means to ignore newlines until "baseurl:"
  A cool website made by Powell-v2.
  No critters were hurt during the making of this website.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# github_username: Powell-v2

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Pavel Ermolin"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
